### ISSUE TITLE
Support for 1.16.5

### ISSUE THREAD

**Issue by James76931** [ataranlen/SimplySpawn#1]
Hi.

Could you please update this for Minecraft 1.16.5?

Thanks
James

**Comment by ataranlen** [comment]
Im currently running this on a 1.16.5 server. What needs fixing?

**Comment by James76931** [comment]
This is the error I am getting when I run the plugin for the first time. It does not enable.
`[22:49:13 ERROR]: Error occurred while enabling SimplySpawn v0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
    at com.minetexas.simplyspawn.util.SSSettings.streamResourceToDisk(SSSettings.java:80) ~[?:?]
    at com.minetexas.simplyspawn.util.SSSettings.loadConfig(SSSettings.java:67) ~[?:?]
    at com.minetexas.simplyspawn.util.SSSettings.loadConfigFiles(SSSettings.java:54) ~[?:?]
    at com.minetexas.simplyspawn.util.SSSettings.init(SSSettings.java:45) ~[?:?]
    at com.minetexas.simplyspawn.SimplySpawn.onEnable(SimplySpawn.java:30) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1051]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1051]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1051]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1051]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1051]
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Purpur-1051]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1051]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1051]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1051]
    at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
    at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Purpur-1051]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1051]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
    ... 15 more`

**Comment by James76931** [comment]
Never mind. I just had to create the config.yml file manually. Oops!
